#!/usr/bin/env node
// Generate src/version.ts from package.json BEFORE tsc runs.
//
// The bun-compiled standalone binary has no package.json on disk, so reading the
// version at runtime returned "unknown" (the "Codeep vunknown" bug). Baking the
// version into a source constant at build time makes it available in BOTH the
// npm/node build and the compiled binary, from a single source of truth.
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const outPath = join(root, 'src', 'version.ts');
const content =
  `// AUTO-GENERATED by scripts/gen-version.js — do not edit by hand.\n` +
  `// Baked from package.json at build time so the bun-compiled binary reports\n` +
  `// the right version (it has no package.json on disk to read at runtime).\n` +
  `export const VERSION = '${version}';\n`;

// Only rewrite when changed, to avoid needless tsc rebuilds and git churn.
if (!existsSync(outPath) || readFileSync(outPath, 'utf-8') !== content) {
  writeFileSync(outPath, content);
  console.log(`Generated src/version.ts → ${version}`);
}
