// AUTO-GENERATED by scripts/gen-version.js — do not edit by hand.
// Baked from package.json at build time so the bun-compiled binary reports
// the right version (it has no package.json on disk to read at runtime).
export const VERSION = '2.13.2';
